name: Deployment Workflow
on:
  push:
    branches:
      - "master"

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn
        run: npm install -g yarn

      - run: yarn install

      - name: Graphql Codegen
        run: yarn codegen

      - name: Type check
        run: yarn typecheck

      # - name: Test GraphQL API
      #   run: yarn run test
      #   env:
      #     NODE_ENV: test

      - name: Run Build
        run: yarn run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate Prisma Client
        run: npx prisma generate --schema prisma/schema_mysql.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: 138.68.127.224
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: /var/www/html/letterpad-admin

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 138.68.127.224
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            pm2 reload letterpad-admin
